name: dustywindow
favicon: null
layout_spectrum: 0.16101
typography_spectrum: 0.20897
title: Through the window
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#332816'
    - '#aeafa7'
    - '#d6d7db'
    - '#7a5a33'
  brandStrength: 0.5
  lightness: 0.3563498533330858
  saturation: 0.5654697322752327
  rhythmicContrast: 0.7536913526710123
purpose: []
